#!/bin/sh
#SBATCH -J UIRP_MD    # Job name
#SBATCH -p 96core          # Partition name
#SBATCH -N 1               # Number of nodes
#SBATCH -n 48              # Number of cores (MPI tasks)
#SBATCH -o %x.o%j          # Standard output file
#SBATCH -e %x.e%j          # Standard error file

export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so # Do not change here!!

# 시간 기록용 파일명 지정
TIME_LOG="time_log_${SLURM_JOB_ID}.txt"

# 시작 시간 기록
echo "Start time: $(date)" > $TIME_LOG

# LAMMPS 실행
mpirun -np 48 /opt/lammps/lammps-stable_29Aug2024/build/lmp -in in.sputtering_ok

# 종료 시간 기록
echo "End time: $(date)" >> $TIME_LOG
