#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import subprocess
import sys
from pathlib import Path

def run(cmd, cwd=None):
    print("▶", " ".join(map(str, cmd)))
    subprocess.run(cmd, check=True, cwd=cwd)

def must_exist(p: Path, what: str):
    if not p.is_file():
        raise FileNotFoundError(f"❌ {what} not found: {p}")

def main():
    ap = argparse.ArgumentParser(description="All-in-one ML agent: dump->csv -> random-train -> auto_best inference")
    ap.add_argument("--workdir", default=".", help="Working directory where dumps/scripts live")
    ap.add_argument("--n_trials", type=int, default=None, help="Override N_TRIALS (optional; edits env only if script supports)")
    ap.add_argument("--infer_samples", type=int, default=5, help="n_samples for inference")
    ap.add_argument("--infer_out", default="pred_samples.csv", help="Output CSV for inference")
    ap.add_argument("--infer_in", default="mdn_input.csv", help="Input CSV for inference (generated by dump2csv)")
    ap.add_argument("--skip_train", action="store_true", help="Skip training step (use existing random_search_summary.json)")
    ap.add_argument("--skip_infer", action="store_true", help="Skip inference step")
    args = ap.parse_args()

    wd = Path(args.workdir).resolve()

    # Required inputs from MD agent
    inc = wd / "incident.dump"
    ref = wd / "reflected.dump"
    must_exist(inc, "incident.dump")
    must_exist(ref, "reflected.dump")

    # Scripts
    dump2csv = wd / "01_Dump2csv.py"
    train_rs = wd / "02_02_Random_Train_Model.py"
    infer_py = wd / "03_Infer_Model.py"
    must_exist(dump2csv, "01_Dump2csv.py")
    must_exist(infer_py, "03_Infer_Model.py")
    if not args.skip_train:
        must_exist(train_rs, "02_02_Random_Train_Model.py")

    print(f"📁 workdir = {wd}")

    # 1) dump -> mdn_input.csv / mdn_output.csv
    run([sys.executable, str(dump2csv)], cwd=wd)

    mdn_in = wd / args.infer_in
    mdn_out = wd / "mdn_output.csv"
    must_exist(mdn_in, "mdn_input.csv (generated)")
    must_exist(mdn_out, "mdn_output.csv (generated)")

    # 2) random search training (creates rs_runs/ and random_search_summary.json)
    if not args.skip_train:
        # NOTE: 02_02_Random_Train_Model.py 내부 N_TRIALS는 하드코딩이라,
        #       n_trials 바꾸려면 그 파일에서 N_TRIALS 값을 바꾸거나, 아래처럼 환경변수로 바꾸는 기능을 추가해야 함.
        run([sys.executable, str(train_rs)], cwd=wd)

    summary = wd / "random_search_summary.json"
    must_exist(summary, "random_search_summary.json (from random training)")

    # 3) inference with auto_best
    if not args.skip_infer:
        pred_out = wd / args.infer_out
        run([
            sys.executable, str(infer_py),
            "--input_csv", str(mdn_in),
            "--output_csv", str(pred_out),
            "--n_samples", str(args.infer_samples),
            "--auto_best",
            "--summary_path", str(summary),
            "--rs_base", "rs_runs",
        ], cwd=wd)

        must_exist(pred_out, "pred_samples.csv (inference output)")
        print(f"✅ All done. Inference saved: {pred_out}")
    else:
        print("⏭ Skipped inference as requested.")

if __name__ == "__main__":
    main()
